// Portfolio content. Add an entry here and drop its thumbnail in public/media/<id>.webp.
// Order doesn't matter: the list sorts newest first.

import type { Entry } from './types';

export const entries: Entry[] = [
  // ---------- Penn (MSE, Computer Graphics & Game Technology) ----------
  {
    id: 'path-tracer',
    kind: 'school',
    title: 'GPU Path Tracer',
    context: 'Penn CIS 5650 · GPU Programming',
    date: '2026-09',
    end: '2026-10',
    description:
      'A physically based GPU path tracer in C++/CUDA with multiple importance sampling and next event estimation, GGX microfacet and refractive materials, HDRI lighting, thin-lens depth of field, and texture/bump mapping for glTF. A median-split BVH cut render time on a 70k-triangle mesh by 960×, with heatmap and leaf-node debug views to profile traversal cost. Stream compaction (thrust) and material sorting (CUB radix sort) gave up to 1.9× speedup in open scenes, and Intel Open Image Denoise runs on the GPU with albedo and normal buffers for interactive denoised previews.',
    thumbnail: '/media/path-tracer.webp',
    thumbAlt: 'Path-traced render of water splashing beside a pufferfish hot-air balloon',
    link: 'https://github.com/Gavin-Sears/Project3-CUDA-Path-Tracer',
    keywords: ['C++', 'CUDA', 'OpenGL', 'Path Tracing'],
    hiddenKeywords: ['ray tracing', 'raytracing', 'GPU', 'BVH', 'denoising', 'OIDN', 'PBR', 'glTF', 'thrust', 'CUB', 'rendering'],
  },
  {
    id: 'gaussian-fluids',
    kind: 'school',
    title: 'Gaussian Fluids',
    context: 'Penn · Advanced Topics in Computer Graphics',
    date: '2026-05',
    description:
      'An implementation of the Gaussian Fluids research paper as a Houdini plugin. The velocity field is represented as Gaussians, simulating fluid motion that preserves more vorticity and uses less memory than typical grid-based solvers.',
    thumbnail: '/media/gaussian-fluids.webp',
    thumbAlt: 'Stanford bunny in Houdini with purple Gaussian vortex rings',
    link: 'https://github.com/Gavin-Sears/Gushin-Gaussians',
    keywords: ['C++', 'C', 'Houdini', 'Simulation'],
    hiddenKeywords: ['fluid simulation', 'physics', 'research paper', 'HDK', 'plugin', 'vorticity'],
  },
  {
    id: 'virtual-aquarium',
    kind: 'school',
    title: 'Virtual Aquarium',
    context: 'Penn CIS 5660 · Procedural Computer Graphics',
    date: '2025-09',
    end: '2025-12',
    description:
      'A procedural WebGL2 renderer with a fish generator that extrudes parameterized ring loops along a body spine, with 20+ real-time parameters and per-frame pivot-based transforms.',
    thumbnail: '/media/virtual-aquarium.webp',
    thumbAlt: 'Procedural fish swimming among colorful seaweed in the virtual aquarium',
    link: 'https://virtual-aquarium-5660.vercel.app',
    keywords: ['WebGL2', 'TypeScript', 'Procedural'],
    hiddenKeywords: ['procedural generation', 'GLSL', 'shaders', 'web', 'real-time', 'fish'],
  },
  {
    id: 'cuda-flocking',
    kind: 'school',
    title: 'CUDA Boids Flocking',
    context: 'Penn CIS 5650 · GPU Programming',
    date: '2026-09',
    description:
      'A GPU boids flocking simulation in CUDA, implemented three ways: a naive O(n²) neighbor search, a scattered uniform grid, and a coherent uniform grid that sorts position and velocity data for contiguous memory reads. An automated benchmark swept boid counts up to 500,000, block sizes from 32 to 1,024, and 8- vs. 27-cell neighborhoods. The coherent grid ran up to 63% faster than the scattered one at 500,000 boids, and the 27-cell search slowed around 50,000 boids as the grid outgrew the L2 cache.',
    thumbnail: '/media/cuda-flocking.webp',
    thumbAlt: 'Swarm of thousands of colored boids flocking in 3D',
    link: 'https://github.com/Gavin-Sears/Project1-CUDA-Flocking',
    keywords: ['CUDA', 'C++', 'OpenGL', 'Simulation'],
    hiddenKeywords: ['boids', 'flocking', 'uniform grid', 'spatial grid', 'GPU', 'parallel programming', 'performance analysis', 'benchmarking', 'memory coherence', 'L2 cache', 'crowd simulation'],
  },
  {
    id: 'stream-compaction',
    kind: 'school',
    title: 'CUDA Stream Compaction',
    context: 'Penn CIS 5650 · GPU Programming',
    date: '2026-09',
    description:
      'Parallel prefix-sum (scan) and stream compaction in CUDA: CPU baselines, naive (Hillis-Steele) and work-efficient (Blelloch) GPU scans, each with and without shared memory, and Thrust for comparison. The shared-memory versions scan per block and recurse on block totals, with bank-conflict-free indexing. Benchmarks from 2¹⁰ to 2³⁰ elements and Nsight Compute profiling traced the slowdowns to kernel-launch overhead, __syncthreads() latency, and low occupancy at deep up-sweep levels.',
    thumbnail: '/media/stream-compaction.webp',
    thumbAlt: 'Log-scale chart of scan time versus array size for CPU, naive, work-efficient, and Thrust scans',
    link: 'https://github.com/Gavin-Sears/Project2-Stream-Compaction',
    keywords: ['CUDA', 'C++', 'Parallel Algorithms'],
    hiddenKeywords: ['scan', 'prefix sum', 'Blelloch', 'Hillis-Steele', 'work-efficient', 'shared memory', 'bank conflicts', 'Thrust', 'Nsight Compute', 'profiling', 'occupancy', 'GPU', 'performance analysis'],
  },
  {
    id: 'courage-farmhouse',
    kind: 'school',
    title: 'Courage the Cowardly Dog: Bagge Farmhouse',
    context: 'Penn DSGN 5005 · 3D Computer Modeling',
    date: '2025-11',
    description:
      'A Maya recreation of the Bagge farmhouse in Nowhere, Kansas, from Courage the Cowardly Dog. A print of the render was shown in the "Rendering… in progress" pop-up exhibition at Penn’s Charles Addams Fine Arts Gallery, November 12–18, 2025.',
    thumbnail: '/media/courage-farmhouse.webp',
    thumbAlt: 'Red farmhouse with a windmill and green truck on a lone hill under a pink sky',
    keywords: ['Maya', '3D Modeling'],
    hiddenKeywords: ['Autodesk Maya', 'modeling', 'texturing', 'lighting', 'rendering', 'environment', 'exhibition', 'gallery', 'cartoon'],
  },
  {
    id: 'procedural-jellyfish',
    kind: 'school',
    title: 'Procedural Jellyfish',
    context: 'Penn CIS 5660 · Procedural Computer Graphics',
    date: '2025-10',
    description:
      'A procedurally generated jellyfish in Houdini, with its bell, arms, veins, organs, and tentacles built from procedural networks. Physics simulations use Vellum solvers cached to disk for performance, and the result is rendered with Mantra.',
    thumbnail: '/media/procedural-jellyfish.webp',
    thumbAlt: 'Glowing green and blue jellyfish with pink frills and coral-colored tentacles on black',
    link: 'https://github.com/Gavin-Sears/hw02-jellyfish-Gavin',
    keywords: ['Houdini', 'Procedural', 'Simulation'],
    hiddenKeywords: ['Vellum', 'Mantra', 'procedural modeling', 'procedural generation', 'rendering', 'physics', 'VFX'],
  },
  {
    id: 'scream-stylization',
    kind: 'school',
    title: 'The Scream: 3D Stylization',
    context: 'Penn CIS 5660 · Procedural Computer Graphics',
    date: '2025-10',
    description:
      'A stylized Unity scene inspired by Edvard Munch’s "The Scream" and Tales from the Crypt. A three-tone smooth toon shader supports multiple lights and shadows, a seamless hand-drawn texture was generated procedurally with Blender shader nodes, and full-screen effects add an animated sky masked by the depth texture, outlines, and vignettes. Keys switch to Party mode (confetti vignette, inverted colors, color-shifting outlines) and a sepia Memory mode.',
    thumbnail: '/media/scream-stylization.webp',
    thumbAlt: 'Toon-shaded figure from The Scream in a purple room under a swirling orange sky',
    link: 'https://github.com/Gavin-Sears/hw02-stylization-Gavin',
    keywords: ['Unity', 'HLSL', 'C#', 'Blender'],
    hiddenKeywords: ['toon shading', 'toon shader', 'NPR', 'non-photorealistic rendering', 'stylized rendering', 'post-processing', 'outlines', 'shaders', 'ShaderLab', 'procedural texture', 'csharp'],
  },
  {
    id: 'procedural-fireball',
    kind: 'school',
    title: 'Procedural Fireball',
    context: 'Penn CIS 5660 · Procedural Computer Graphics',
    date: '2025-09',
    description:
      'An animated fireball in WebGL2 and TypeScript, shaped by vertex displacement from 3D fractal Brownian motion (FBM) noise in GLSL. GUI sliders control energy (color palette), life (flame height), and vitality (speed and amount of movement), and the fireball can be moved with the mouse.',
    thumbnail: '/media/procedural-fireball.webp',
    thumbAlt: 'Magenta-to-orange procedural fireball with a flickering tail',
    link: 'https://gavinsears.dev/hw01-fireball-Gavin/',
    keywords: ['TypeScript', 'WebGL2', 'GLSL', 'Procedural'],
    hiddenKeywords: ['noise', 'FBM', 'fractal noise', 'value noise', 'vertex displacement', 'shaders', 'dat.GUI', 'webpack', 'fire', 'VFX', 'web'],
  },

  // ---------- Penn coursework from private class repos (no public link) ----------
  {
    id: 'fk-ik-character-animation',
    kind: 'school',
    title: 'FK/IK Character Animation',
    context: 'Penn CIS 5620 · Computer Animation',
    date: '2025-10',
    description:
      'Skeletal animation for an FBX character: forward kinematics plays BVH motion-capture clips through the joint hierarchy, an analytic limb IK solver bends arms and legs with the law of cosines, and foot IK aligns the feet to the ground normal.',
    thumbnail: '/media/fk-ik-character-animation.webp',
    thumbAlt: 'Animated character dancing Gangnam Style from BVH motion capture',
    keywords: ['C++', 'OpenGL', 'Animation'],
    hiddenKeywords: ['forward kinematics', 'inverse kinematics', 'FK', 'IK', 'BVH', 'motion capture', 'mocap', 'skeleton', 'FBX', 'Jacobian', 'character animation'],
  },
  {
    id: 'curve-editor',
    kind: 'school',
    title: 'Spline & Rotation Curve Editor',
    context: 'Penn CIS 5620 · Computer Animation',
    date: '2025-10',
    description:
      'A curve and rotation interpolation library with an interactive editor. Curves can be linear, Bézier (Bernstein, de Casteljau, and matrix forms), or Hermite splines solved as a linear system with Eigen. Rotations convert between Euler angles, matrices, quaternions, and axis-angle, and interpolate with Slerp and quaternion Bézier curves, compared side by side on animated models.',
    thumbnail: '/media/curve-editor.webp',
    thumbAlt: 'Bézier curve with its control points and tangent handles in the curve editor',
    keywords: ['C++', 'Eigen', 'OpenGL', 'Animation'],
    hiddenKeywords: ['splines', 'Bezier', 'de Casteljau', 'Hermite', 'quaternions', 'Slerp', 'Euler angles', 'interpolation', 'keyframing', 'linear algebra'],
  },
  {
    id: 'mesh-editor',
    kind: 'school',
    title: 'Half-Edge Mesh Editor',
    context: 'Penn CIS 5600 · Interactive Computer Graphics',
    date: '2025-05',
    description:
      'A Maya-like polygon mesh editor built on a half-edge data structure. It imports OBJ files, lets you select vertices, half-edges, and faces (with visual debugging and keyboard traversal between them), edit positions and face colors, and run topology operations: edge splitting, face triangulation, and Catmull-Clark subdivision.',
    thumbnail: '/media/mesh-editor.webp',
    thumbAlt: 'Mesh editor window with a cow model in random face colors beside vertex, half-edge, and face lists',
    keywords: ['C++', 'OpenGL', 'Qt', '3D Modeling'],
    hiddenKeywords: ['half-edge', 'half edge', 'Catmull-Clark', 'subdivision', 'triangulation', 'topology', 'OBJ', 'mesh', 'geometry processing'],
  },
  {
    id: 'surface-post-process-shaders',
    kind: 'school',
    title: 'Surface & Post-Process Shaders',
    context: 'Penn CIS 5600 · Interactive Computer Graphics',
    date: '2025-02',
    description:
      'GLSL surface shaders (Lambert, Blinn-Phong, matcap with six materials, and a custom vertex-deformation shader that melts the model into animated goo) and framebuffer post-processing passes: Sobel edge detection, Gaussian blur, and a custom animated Voronoi (Worley) noise effect. The scene is viewed with a polar spherical orbit camera.',
    thumbnail: '/media/surface-post-process-shaders.webp',
    thumbAlt: 'Mario scene with a Sobel edge-detection post-process, glowing outlines on black',
    keywords: ['GLSL', 'OpenGL', 'C++', 'Qt'],
    hiddenKeywords: ['post-processing', 'framebuffer', 'render to texture', 'Worley noise', 'Voronoi', 'Sobel', 'edge detection', 'Gaussian blur', 'matcap', 'Blinn-Phong', 'Lambert', 'vertex shader', 'noise', 'shaders'],
  },
  {
    id: 'software-rasterizer',
    kind: 'school',
    title: 'Software Rasterizer',
    context: 'Penn CIS 5600 · Interactive Computer Graphics',
    date: '2025-02',
    description:
      'A CPU rasterizer written from scratch in C++ that renders textured 3D meshes through a full pipeline: camera and perspective projection, triangle rasterization with barycentric coordinates, perspective-correct interpolation, a z-buffer, and texture mapping. Extra features include normal mapping, Blinn-Phong and toon reflection models, and an animated rainbow color mode.',
    thumbnail: '/media/software-rasterizer.webp',
    thumbAlt: 'Toon-shaded Mario rendered by the software rasterizer',
    keywords: ['C++', 'Qt', 'Rendering'],
    hiddenKeywords: ['rasterization', 'rasterizer', 'barycentric coordinates', 'z-buffer', 'depth buffer', 'perspective projection', 'texture mapping', 'normal mapping', 'Blinn-Phong', 'toon shading', 'graphics pipeline', 'CPU rendering'],
  },

  // ---------- Earlier projects (from the old site) ----------
  // Dates are the last relevant update.
  {
    id: 'high-score',
    kind: 'school',
    title: 'High Score',
    context: 'VCAM installation · Haverford College',
    date: '2024-12',
    description:
      'An iPad game installed at the VCAM, which ran continuously (including overnight) from 12/11/24 to 12/19/24 without performance or memory issues. It features 6 textured, game-optimized 3D models, 3 animations for the main character, 3 shaders (shell-texture grass, flowing water, sprite animation) in GLSL and Metal, an original soundtrack made in FL Studio, an autosave system for game state and the leaderboard, and basic LOD with looping levels.',
    thumbnail: '/media/high-score.webp',
    thumbAlt: 'Red cart driving across a grassy level in High Score',
    link: 'https://www.instagram.com/p/DDXg7ZnJIdU/',
    keywords: ['Swift', 'Metal', 'GLSL', 'Blender'],
    hiddenKeywords: ['iOS', 'iPad', 'Xcode', 'FL Studio', 'GIMP', 'shaders', 'game', 'shell texturing', 'LOD', 'music'],
  },
  {
    id: 'game-programming-demos',
    kind: 'school',
    title: 'Game Programming Demos',
    context: 'CS 283 · Game Programming',
    date: '2024-12',
    description: 'Game programming demos in C# and Unity, including a 3D platformer, particle systems, enemy AI, and material swapping system that makes objects transparent when in front of the player.',
    thumbnail: '/media/game-programming-demos.webp',
    thumbAlt: 'Marble bust struck by a volley of arrows in a Unity scene',
    link: 'https://github.com/Gavin-Sears/cs283-f24-assignments',
    keywords: ['C#', 'Unity', 'Blender'],
    hiddenKeywords: ['game', 'game programming', 'csharp'],
  },
  {
    id: 'model-editor',
    kind: 'school',
    title: '3D Model Editor',
    date: '2023-05',
    description:
      'An easy-to-use 3D model creator: build something out of cubes, then decorate it with 3D models whose color, size, and rotation can be changed.',
    thumbnail: '/media/model-editor.webp',
    thumbAlt: 'Flexing cube-built monster with red horns and a green eye, made in the model editor',
    link: 'https://github.com/Gavin-Sears/popit-decorations/tree/main',
    keywords: ['C++', 'OpenGL', 'GLSL', 'Blender'],
    hiddenKeywords: ['tools', 'editor', 'voxel', 'shaders'],
  },
  {
    id: 'particle-effects',
    kind: 'school',
    title: 'Particle Effects',
    date: '2023-04',
    description: 'Particle effects built in C++ and OpenGL.',
    thumbnail: '/media/particle-effects.webp',
    thumbAlt: 'Dazed character with yellow chick particles circling its head',
    link: 'https://github.com/Gavin-Sears/popit-decorations/tree/main',
    keywords: ['C++', 'OpenGL', 'Blender'],
    hiddenKeywords: ['particles', 'VFX', 'effects'],
  },
  {
    id: 'vertex-animation',
    kind: 'personal',
    title: 'Vertex Animation Shaders & GPU Instancing',
    date: '2023-08',
    description:
      'Two Blender animations (an egg creature running, and a physics-simulated book page turning) baked into textures, played back by two custom Unity URP Shader Graph shaders: one animates a mesh from a texture and an extra UV set, the other scrubs through vertex-animation frames from scripts. Many meshes can animate at once while still using GPU instancing to reduce draw calls, and baked physics animations come into Unity with little effort. Some features of the game were removed for this demo.',
    thumbnail: '/media/vertex-animation.webp',
    thumbAlt: 'Crowd of instanced egg creatures in a Unity scene',
    keywords: ['C#', 'Unity', 'Shader Graph', 'Python', 'Blender', 'UI/UX Design'],
    hiddenKeywords: ['VAT', 'vertex animation textures', 'instancing', 'URP', 'shaders', 'csharp', 'optimization'],
  },
  {
    id: 'ui-design-case-study',
    kind: 'school',
    title: 'UI Design Case Study',
    date: '2024-12',
    description: 'A UI design case study on a podcast app design. Did three user interviews, and surveyed 25 others. UI design made in Figma.',
    thumbnail: '/media/ui-design-case-study.webp',
    thumbAlt: 'Grid of mobile app screens from the Figma case study',
    link: 'https://www.figma.com/design/8yJfaDqdGnJPYAPANhWVV8/Gavin---Design?node-id=145-59871',
    keywords: ['Figma', 'UI/UX Design', 'User Research'],
    hiddenKeywords: ['design', 'prototype', 'user interface', 'user interviews', 'surveys', 'UX research', 'usability', 'mobile app', 'podcast'],
  },
  {
    id: 'word-wizard',
    kind: 'personal',
    title: 'Word Wizard',
    context: 'Lemon Dragon Studio · Co-founder',
    date: '2023-07',
    description:
      'An educational ESL game that teaches conversational and writing skills through gamified drills, by Lemon Dragon Studio, which I co-founded. I created the 3D models, oversaw most of the UI design, and wrote a large share of the software, including the UI and the code for one of the three minigames. Currently unreleased; we plan to finish optimizing the UI and some scenes and publish it on itch.io.',
    thumbnail: '/media/word-wizard.webp',
    thumbAlt: 'Mushroom wizard character model from Word Wizard',
    link: 'https://www.instagram.com/p/CzWk3BmMhsi/',
    keywords: ['C#', 'Unity', 'Blender', 'UI/UX Design'],
    hiddenKeywords: ['game', 'education', 'ESL', 'Shader Graph', 'GIMP', 'startup', 'csharp', '3D modeling'],
  },
];
